Do not run main.py in its current state. 

A RecursionError prevents a successful execution.
Cause is known but has not been fixed yet